"""NEXUS IMS — Automated Replenishment Celery Tasks."""
import asyncio
import logging

from app.db.base import async_session_maker
from app.models.tenant import Tenant
from app.models.warehouse import Warehouse
from app.services.report_service import ReportService
from app.services.purchase_order_service import PurchaseOrderService
from app.worker import celery_app
from sqlalchemy import select

logger = logging.getLogger(__name__)


async def _generate_replenishment_pos():
    """Finds all low stock SKUs across all tenants and creates DRAFT Purchase Orders."""
    async with async_session_maker() as db:
        # Get all active tenants
        tenants = (await db.execute(select(Tenant).where(Tenant.is_active == True))).scalars().all()
        
        for tenant in tenants:
            try:
                # Find low stock SKUs for this tenant
                low_skus = await ReportService.get_low_stock_skus(db, tenant.id)
                if not low_skus:
                    continue
                
                # Get a default warehouse. In a real app we might create a PO per warehouse 
                # or have a main receiving warehouse. We'll pick the first active one.
                warehouses = (await db.execute(select(Warehouse).where(
                    Warehouse.tenant_id == tenant.id,
                    Warehouse.is_active == True
                ))).scalars().all()
                
                if not warehouses:
                    logger.warning(f"Tenant {tenant.id} has low stock but no active warehouses. Skipping.")
                    continue
                    
                default_warehouse = warehouses[0]
                
                # Group SKUs (for MVP, put them all in one PO. Later, group by default_supplier)
                lines = []
                for sku in low_skus:
                    deficit = sku["deficit"]
                    if deficit <= 0:
                        continue
                    
                    # Order enough to get back to reorder_point + some buffer, or just the deficit 
                    # Usually order to get back to max_stock, but we don't have max_stock. 
                    # We'll just order the deficit + 10 as a simple heuristic so they aren't immediately low again.
                    order_qty = deficit + 10
                    
                    lines.append({
                        "sku_id": sku["sku_id"],
                        "quantity_ordered": float(order_qty),
                        "unit_cost": sku["unit_cost"] or 0.0,
                    })
                
                if lines:
                    po = await PurchaseOrderService.create_po(
                        db=db,
                        tenant_id=tenant.id,
                        supplier_name="Auto-Replenish Supplier (System)",
                        warehouse_id=default_warehouse.id,
                        lines=lines,
                        notes=f"Auto-generated by Replenishment Engine for {len(lines)} low-stock SKUs."
                    )
                    logger.info(f"Created auto-replenishment PO {po.id} for tenant {tenant.id} with {len(lines)} lines")
            
            except Exception as e:
                logger.error(f"Failed to process auto-replenishment for tenant {tenant.id}: {e}")
                
        await db.commit()


@celery_app.task(name="app.tasks.replenishment_tasks.generate_replenishment_pos")
def trigger_replenishment_pos():
    """Celery task wrapper for async auto-replenishment logic."""
    asyncio.run(_generate_replenishment_pos())

