"""add_rma_and_multi_currency

Revision ID: 0e0bff13f29a
Revises: 72dd65a116dc
Create Date: 2026-02-22 04:08:00.835082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e0bff13f29a'
down_revision: Union[str, None] = '72dd65a116dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('module_installs_tenant_id_fkey', 'module_installs', type_='foreignkey')
    op.create_foreign_key(None, 'module_installs', 'tenants', ['tenant_id'], ['id'], source_schema='public', ondelete='CASCADE')
    op.add_column('purchase_orders', sa.Column('currency_code', sa.String(length=3), nullable=False))
    op.add_column('purchase_orders', sa.Column('exchange_rate', sa.Numeric(precision=14, scale=6), nullable=False))
    op.add_column('tenants', sa.Column('base_currency', sa.String(length=3), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'base_currency')
    op.drop_column('purchase_orders', 'exchange_rate')
    op.drop_column('purchase_orders', 'currency_code')
    op.drop_constraint(None, 'module_installs', schema='public', type_='foreignkey')
    op.create_foreign_key('module_installs_tenant_id_fkey', 'module_installs', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
