"""Add serial_numbers table

Revision ID: 72dd65a116dc
Revises: 61eeeff54818
Create Date: 2026-02-21 16:57:55.784281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72dd65a116dc'
down_revision: Union[str, None] = '61eeeff54818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('serial_numbers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('sku_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('serial_number', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('module_installs_tenant_id_fkey', 'module_installs', type_='foreignkey')
    op.create_foreign_key(None, 'module_installs', 'tenants', ['tenant_id'], ['id'], source_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'module_installs', schema='public', type_='foreignkey')
    op.create_foreign_key('module_installs_tenant_id_fkey', 'module_installs', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_table('serial_numbers')
    # ### end Alembic commands ###
