"""block_9_10_workflows

Revision ID: a7f12884ef02
Revises: 0008
Create Date: 2026-02-21 00:57:46.392928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7f12884ef02'
down_revision: Union[str, None] = '0008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('secret', sa.String(length=255), nullable=False),
    sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('trigger_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('webhook_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.String(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('action_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('trigger_event_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('trigger_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('conditions_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actions_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_assembly_orders_status', table_name='assembly_orders')
    op.drop_index('ix_assembly_orders_tenant_id', table_name='assembly_orders')
    op.drop_index('ix_assembly_orders_warehouse_id', table_name='assembly_orders')
    op.drop_table('assembly_orders')
    op.alter_column('api_keys', 'key_prefix',
               existing_type=sa.VARCHAR(length=12),
               comment=None,
               existing_comment='First 8 chars of raw key for identification',
               existing_nullable=False)
    op.alter_column('api_keys', 'key_hash',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='bcrypt hash of raw key',
               existing_nullable=False)
    op.drop_index('ix_api_keys_key_prefix', table_name='api_keys')
    op.drop_index('ix_api_keys_tenant_id', table_name='api_keys')
    op.drop_index('ix_audit_log_actor_id', table_name='audit_log')
    op.drop_index('ix_audit_log_created_at', table_name='audit_log')
    op.drop_index('ix_audit_log_tenant_id', table_name='audit_log')
    op.drop_index('ix_bom_lines_bom_id', table_name='bom_lines')
    op.drop_index('ix_bom_lines_component_sku_id', table_name='bom_lines')
    op.drop_index('ix_boms_finished_sku_id', table_name='boms')
    op.drop_index('ix_boms_tenant_id', table_name='boms')
    op.drop_index('ix_invitation_tokens_email', table_name='invitation_tokens')
    op.drop_index('ix_invitation_tokens_tenant_id', table_name='invitation_tokens')
    op.drop_index('ix_item_types_tenant_id', table_name='item_types')
    op.drop_constraint('uq_item_types_tenant_code', 'item_types', type_='unique')
    op.alter_column('locations', 'location_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_index('ix_locations_parent_id', table_name='locations')
    op.drop_index('ix_locations_warehouse_id', table_name='locations')
    op.drop_constraint('uq_locations_warehouse_code', 'locations', type_='unique')
    op.drop_index('ix_purchase_order_lines_po_id', table_name='purchase_order_lines')
    op.drop_index('ix_purchase_order_lines_sku_id', table_name='purchase_order_lines')
    op.alter_column('purchase_orders', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               comment=None,
               existing_comment='purchase_order_status enum',
               existing_nullable=False,
               existing_server_default=sa.text("'DRAFT'::text"))
    op.drop_index('ix_purchase_orders_status', table_name='purchase_orders')
    op.drop_index('ix_purchase_orders_tenant_id', table_name='purchase_orders')
    op.drop_index('ix_purchase_orders_warehouse_id', table_name='purchase_orders')
    op.drop_index('idx_skus_attributes', table_name='skus', postgresql_using='gin')
    op.drop_index('ix_skus_item_type_id', table_name='skus')
    op.drop_index('ix_skus_tenant_id', table_name='skus')
    op.drop_constraint('uq_skus_tenant_code', 'skus', type_='unique')
    op.alter_column('stock_ledger', 'event_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_index('ix_stock_ledger_created_at', table_name='stock_ledger')
    op.drop_index('ix_stock_ledger_reference_id', table_name='stock_ledger')
    op.drop_index('ix_stock_ledger_tenant_sku_warehouse', table_name='stock_ledger')
    op.drop_index('ix_stock_ledger_warehouse_id', table_name='stock_ledger')
    op.drop_column('stock_ledger', 'unit_cost_snapshot')
    op.drop_index('ix_transfer_order_lines_transfer_order_id', table_name='transfer_order_lines')
    op.alter_column('transfer_orders', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::text"))
    op.drop_index('ix_transfer_orders_from_warehouse', table_name='transfer_orders')
    op.drop_index('ix_transfer_orders_status', table_name='transfer_orders')
    op.drop_index('ix_transfer_orders_to_warehouse', table_name='transfer_orders')
    op.drop_index('ix_user_roles_user_id', table_name='user_roles')
    op.alter_column('users', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'FLOOR_ASSOCIATE'::text"))
    op.alter_column('users', 'warehouse_scope',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='NULL = all warehouses (Admin). List of warehouse UUID strings for scoped roles.',
               existing_nullable=True)
    op.drop_index('ix_users_tenant_email', table_name='users')
    op.drop_index('ix_users_tenant_id', table_name='users')
    op.alter_column('warehouses', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'UTC'::character varying"))
    op.drop_index('ix_warehouses_tenant_id', table_name='warehouses')
    op.drop_constraint('uq_warehouses_tenant_code', 'warehouses', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_warehouses_tenant_code', 'warehouses', ['tenant_id', 'code'])
    op.create_index('ix_warehouses_tenant_id', 'warehouses', ['tenant_id'], unique=False)
    op.alter_column('warehouses', 'timezone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'UTC'::character varying"))
    op.create_index('ix_users_tenant_id', 'users', ['tenant_id'], unique=False)
    op.create_index('ix_users_tenant_email', 'users', ['tenant_id', 'email'], unique=True)
    op.alter_column('users', 'warehouse_scope',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='NULL = all warehouses (Admin). List of warehouse UUID strings for scoped roles.',
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'FLOOR_ASSOCIATE'::text"))
    op.create_index('ix_user_roles_user_id', 'user_roles', ['user_id'], unique=False)
    op.create_index('ix_transfer_orders_to_warehouse', 'transfer_orders', ['to_warehouse_id'], unique=False)
    op.create_index('ix_transfer_orders_status', 'transfer_orders', ['status'], unique=False)
    op.create_index('ix_transfer_orders_from_warehouse', 'transfer_orders', ['from_warehouse_id'], unique=False)
    op.alter_column('transfer_orders', 'status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::text"))
    op.create_index('ix_transfer_order_lines_transfer_order_id', 'transfer_order_lines', ['transfer_order_id'], unique=False)
    op.add_column('stock_ledger', sa.Column('unit_cost_snapshot', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True))
    op.create_index('ix_stock_ledger_warehouse_id', 'stock_ledger', ['warehouse_id'], unique=False)
    op.create_index('ix_stock_ledger_tenant_sku_warehouse', 'stock_ledger', ['tenant_id', 'sku_id', 'warehouse_id'], unique=False)
    op.create_index('ix_stock_ledger_reference_id', 'stock_ledger', ['reference_id'], unique=False)
    op.create_index('ix_stock_ledger_created_at', 'stock_ledger', ['created_at'], unique=False)
    op.alter_column('stock_ledger', 'event_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_unique_constraint('uq_skus_tenant_code', 'skus', ['tenant_id', 'sku_code'])
    op.create_index('ix_skus_tenant_id', 'skus', ['tenant_id'], unique=False)
    op.create_index('ix_skus_item_type_id', 'skus', ['item_type_id'], unique=False)
    op.create_index('idx_skus_attributes', 'skus', ['attributes'], unique=False, postgresql_using='gin')
    op.create_index('ix_purchase_orders_warehouse_id', 'purchase_orders', ['warehouse_id'], unique=False)
    op.create_index('ix_purchase_orders_tenant_id', 'purchase_orders', ['tenant_id'], unique=False)
    op.create_index('ix_purchase_orders_status', 'purchase_orders', ['status'], unique=False)
    op.alter_column('purchase_orders', 'status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               comment='purchase_order_status enum',
               existing_nullable=False,
               existing_server_default=sa.text("'DRAFT'::text"))
    op.create_index('ix_purchase_order_lines_sku_id', 'purchase_order_lines', ['sku_id'], unique=False)
    op.create_index('ix_purchase_order_lines_po_id', 'purchase_order_lines', ['po_id'], unique=False)
    op.create_unique_constraint('uq_locations_warehouse_code', 'locations', ['warehouse_id', 'code'])
    op.create_index('ix_locations_warehouse_id', 'locations', ['warehouse_id'], unique=False)
    op.create_index('ix_locations_parent_id', 'locations', ['parent_id'], unique=False)
    op.alter_column('locations', 'location_type',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_unique_constraint('uq_item_types_tenant_code', 'item_types', ['tenant_id', 'code'])
    op.create_index('ix_item_types_tenant_id', 'item_types', ['tenant_id'], unique=False)
    op.create_index('ix_invitation_tokens_tenant_id', 'invitation_tokens', ['tenant_id'], unique=False)
    op.create_index('ix_invitation_tokens_email', 'invitation_tokens', ['email'], unique=False)
    op.create_index('ix_boms_tenant_id', 'boms', ['tenant_id'], unique=False)
    op.create_index('ix_boms_finished_sku_id', 'boms', ['finished_sku_id'], unique=False)
    op.create_index('ix_bom_lines_component_sku_id', 'bom_lines', ['component_sku_id'], unique=False)
    op.create_index('ix_bom_lines_bom_id', 'bom_lines', ['bom_id'], unique=False)
    op.create_index('ix_audit_log_tenant_id', 'audit_log', ['tenant_id'], unique=False)
    op.create_index('ix_audit_log_created_at', 'audit_log', ['created_at'], unique=False)
    op.create_index('ix_audit_log_actor_id', 'audit_log', ['actor_id'], unique=False)
    op.create_index('ix_api_keys_tenant_id', 'api_keys', ['tenant_id'], unique=False)
    op.create_index('ix_api_keys_key_prefix', 'api_keys', ['key_prefix'], unique=False)
    op.alter_column('api_keys', 'key_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='bcrypt hash of raw key',
               existing_nullable=False)
    op.alter_column('api_keys', 'key_prefix',
               existing_type=sa.VARCHAR(length=12),
               comment='First 8 chars of raw key for identification',
               existing_nullable=False)
    op.create_table('assembly_orders',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('bom_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('bom_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('warehouse_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('planned_qty', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=False),
    sa.Column('produced_qty', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('waste_qty', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('waste_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cogs_per_unit', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bom_id'], ['boms.id'], name='assembly_orders_bom_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='assembly_orders_created_by_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='assembly_orders_tenant_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name='assembly_orders_warehouse_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='assembly_orders_pkey')
    )
    op.create_index('ix_assembly_orders_warehouse_id', 'assembly_orders', ['warehouse_id'], unique=False)
    op.create_index('ix_assembly_orders_tenant_id', 'assembly_orders', ['tenant_id'], unique=False)
    op.create_index('ix_assembly_orders_status', 'assembly_orders', ['status'], unique=False)
    op.drop_table('workflow_executions')
    op.drop_table('workflow_actions')
    op.drop_table('webhook_deliveries')
    op.drop_table('workflows')
    op.drop_table('webhooks')
    # ### end Alembic commands ###
