"""block_9_10_workflows_webhooks

Revision ID: cf46dc601d7f
Revises: a7f12884ef02
Create Date: 2026-02-21 00:58:16.857766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf46dc601d7f'
down_revision: Union[str, None] = 'a7f12884ef02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
